name: nextcloud-aio
working_dir: manual-install
environment:
  AIO_LOG_LEVEL: "warn"
  TIMEZONE: "Europe/Berlin"
  NC_DOMAIN: "cloud.mv-angelbachtal.de"
  CLAMAV_ENABLED: "no"
  COLLABORA_ENABLED: "yes"
  EUROOFFICE_ENABLED: "no"
  FULLTEXTSEARCH_ENABLED: "yes"
  HARP_ENABLED: "no"
  IMAGINARY_ENABLED: "yes"
  ONLYOFFICE_ENABLED: "no"
  TALK_ENABLED: "yes"
  TALK_PORT: "3478"
  TALK_RECORDING_ENABLED: "no"
  WHITEBOARD_ENABLED: "yes"
  APACHE_IP_BINDING: "127.0.0.1"
  APACHE_PORT: "80"
  APACHE_MAX_SIZE: "1073741824"
  ADDITIONAL_COLLABORA_OPTIONS: "['--o:security.seccomp=true']"
  COLLABORA_DICTIONARIES: "de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru"
  COLLABORA_LOG_LEVEL: "warning"
  FULLTEXTSEARCH_JAVA_OPTIONS: "-Xms512M -Xmx512M"
  INSTALL_LATEST_MAJOR: "no"
  NEXTCLOUD_ADDITIONAL_APKS: "imagemagick ocrmypdf tesseract-ocr-data-eng tesseract-ocr-data-deu"
  NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: "imagick"
  NEXTCLOUD_MAX_TIME: "3600"
  NEXTCLOUD_MEMORY_LIMIT: "512M"
  NEXTCLOUD_MOUNT: "/mnt"
  NEXTCLOUD_DATADIR: "nextcloud_aio_nextcloud_data"
  NEXTCLOUD_STARTUP_APPS: "deck twofactor_totp tasks calendar contacts notes"
  NEXTCLOUD_TRUSTED_CACERTS_DIR: "/usr/local/share/ca-certificates/my-custom-ca"
  NEXTCLOUD_UPLOAD_LIMIT: "1G"
  REMOVE_DISABLED_APPS: "yes"
  UPDATE_NEXTCLOUD_APPS: "no"
  WATCHTOWER_DOCKER_SOCKET_PATH: "/var/run/docker.sock"
profiles:
  - collabora
  - talk
  - imaginary
  - fulltextsearch
  - whiteboard
compose_files:
  - compose.yaml
  - compose.override.yaml
